n1 = int(input('Digite um número para ver sua tabuada: '))
i = n1 * int(1)
II = n1 * int(2)
III = n1 * int(3)
IV = n1 * int(4)
V = n1 * int(5)
VI = n1 * int(6)
VII = n1 * int(7)
VIII = n1 * int(8)
IX = n1 * int(9)
X = n1 * int(10)
print('A tabuada de {} é '.format(n1))
print('1x={} 2x={} 3x={}'.format(i, II, III))
print('4x={} 5x={} 6x={}'.format(IV, V, VI))
print('7x={} 8x={} 9x={}'.format(VII, VIII, IX))
print('10x={}'.format(X))
