nome = str(input('Digite o nome completo: ')).strip()
#up = nome.upper()
#lo = nome.lower()
#qua = len(nome) - nome.count(' ')
#p1 =  nome.split()
#nome1 = p1[0]
#p2 = len(nome1)
#print('O nome {} em:'.format(nome))
#print('Letras Maisculas: {}'.format(up))
#print('Letras Minusculas: {}'.format(lo))
#print('Quantas Letras sem espaço? {}'.format(qua))
#print('Quantas letras tem o primeiro nome: {}'.format(p2))
p1 = nome.split()
print('Analisando seu nome...')
print('Seu nome em letras maiúsculas é: {}'.format(nome.upper()))
print('Seu nome em letras minúsculas é: {}'.format(nome.lower()))
print('A quantidade de letras em seu nome é: {}'.format(len(nome) - nome.count(' ')))
#print('Quantidade de letras no primeiro nome: {}'.format(len(p1[0])))
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
